// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  spaces = 32,
  LineComment = 1,
  Program = 2,
  Identifier = 3,
  Parameter = 6,
  BinaryExpression = 8,
  Number = 9,
  FunctionDeclaration = 16,
  OperatorDeclaration = 18,
  Operator = 20,
  ListDeclaration = 21,
  ListIdentifier = 22,
  newline = 45
