// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 13,
  states: "#xQYQPOOObQPO'#CjO!PQPO'#CeOOQO'#Cj'#CjQYQPOOO!kQQO,59VOYQPO,58}OYQPO,58}OYQPO,58}OYQPO,58}OYQPO,58}OOQO-E6c-E6cOOQO'#Cf'#CfO!sQQO1G.qOOQO1G.q1G.qOOQO1G.i1G.iO#dQPO1G.iO#kQPO1G.iO$ZQPO1G.iO$bQPO1G.iOOQO-E6d-E6dOOQO7+$]7+$]",
  stateData: "$i~O]OSPOS~ORPOWRO~OSTOR^XW^XZ^X`^Xa^Xb^Xc^Xd^X~O`UOaVObWOcXOdYORXXWXXZXX~OT[OU^O~OT[OUeO~O`UORViWViZVibVicVidVi~OaVi~P!{OaVO~P!{O`UOaVObWORViWViZVidVi~OcVi~P#rOcXO~P#rO",
  goto: "!Z`PPPPPPPaPjpPPPva_ROSUVWXYQSORZSQ]TRd]SQOSQ_UQ`VQaWQbXRcY",
  nodeNames: "⚠ LineComment Program Identifier ( Parameter ) BinaryExpression Number",
  maxTerm: 20,
  skippedNodes: [0,1],
  repeatNodeCount: 2,
  tokenData: "$|~RaXY!W[]!Wpq!Wst!rtu#Qxy#kyz#pz{#u{|$S}!O$X!P!Q$^!Q![$c!c!}#Q#O#P!i#R#S#Q#T#o#Q$g~#Q~!]S]~XY!W[]!Wpq!W#O#P!i~!lQYZ!W]^!W~!wRP~OY!rZ]!r^~!rR#XURPTQtu#Q!Q![#Q!c!}#Q#R#S#Q#T#o#Q$g~#Q~#pOS~~#uOU~~#zPa~z{#}~$SO`~~$XOc~~$^Od~~$cOb~~$hQW~!O!P$n!Q![$c~$qP!Q![$t~$yPW~!Q![$t",
  tokenizers: [0, 1],
  topRules: {"Program":[0,2]},
  tokenPrec: 0
})
