// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  spaces = 13,
  LineComment = 1,
  Program = 2,
  Identifier = 3,
  Parameter = 5,
  BinaryExpression = 7,
  Number = 8
